# Generated by Django 3.0.5 on 2020-04-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='timings',
            new_name='class_duration',
        ),
    ]
