# Generated by Django 3.0.5 on 2020-04-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200406_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Branche',
        ),
    ]
